name: GHCR

on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-24.04
    permissions:
      # Needed to write to the ghcr.io registry
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Mirror DockerHub
        run: |
          image="ubuntu:18.04"
          docker pull docker.io/$image
          docker tag $image ghcr.io/${{ github.repository_owner }}/$image
          docker push ghcr.io/${{ github.repository_owner }}/$image
        shell: bash
