name: GHCR

on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-24.04
    permissions:
      # Needed to write to the ghcr.io registry
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Mirror DockerHub
        run: python3 src/ci/github-actions/ghcr.py
        shell: bash
